# Generated by Django 2.1.5 on 2019-03-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kekka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('student_code', models.CharField(blank=True, max_length=10)),
                ('date', models.DateField()),
                ('reason', models.CharField(max_length=1000)),
            ],
        ),
    ]
