# Generated by Django 2.1.5 on 2019-02-17 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kekkatodoke', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sutudent_class',
            new_name='student_class',
        ),
    ]
