# Generated by Django 2.1.5 on 2019-02-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kekkatodoke', '0002_auto_20190217_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_name',
            field=models.CharField(default='kawamoto', max_length=50),
            preserve_default=False,
        ),
    ]
